### ISSUE TITLE
UDP ports usage

### ISSUE THREAD

**Issue by pettai** [cloudmon360/grideye_agent#3]
Using UDP can be an issue as some network block it by default.
So to make UDP usage a little leaner, either: 
- If the first UDP connection between client-server fails, switch the UDP port used to the traceroute port range (UDP ports 33434-33600)

alternatively

- Default to the UDP port range that traceroute uses.

**Comment by krihal** [comment]
The communication are now by default using HTTPS, is this still needed?

**Comment by krihal** [comment]
Invalid since communication is now done over HTTP(S).
